### ISSUE TITLE
ROW Authentication + AssetBundles

### ISSUE THREAD

**Issue by YumYummity** [mos9527/sssekai#17]
I've been using the TW credential to get data, but this seems to constantly expire and need me to go back and find the new one.

Is there any way to setup a guest account? (maybe with an email).

Or, there is a request to `https://gsdk-sg.bytegsdk.com/gsdk/account/login` that could be done via the library?

Also, I couldn't extract the asset bundles from the TW server. Loading the asset bundle gives me an error, compared to EN/JP ABs.
```python
  File "C:\Users\YumYummity\Desktop\bot\twitch\pjsk\DATA\game_api\ab_extract.py", line 224, in extract
    env: Environment = self.load()
  File "C:\Users\YumYummity\Desktop\bot\twitch\pjsk\DATA\game_api\ab_extract.py", line 37, in load
    return UnityPy.load(str(self.path))
  File "C:\Development\Python\Python3.10.6\lib\site-packages\UnityPy\__init__.py", line 10, in load
    return Environment(*args, fs=fs, **kwargs)
  File "C:\Development\Python\Python3.10.6\lib\site-packages\UnityPy\environment.py", line 46, in __init__
    self.load_file(arg)
  File "C:\Development\Python\Python3.10.6\lib\site-packages\UnityPy\environment.py", line 144, in load_file
    f = ImportHelper.parse_file(
  File "C:\Development\Python\Python3.10.6\lib\site-packages\UnityPy\helpers\ImportHelper.py", line 139, in parse_file
    f = files.BundleFile(reader, parent, name=name, is_dependency=is_dependency)
  File "C:\Development\Python\Python3.10.6\lib\site-packages\UnityPy\files\BundleFile.py", line 42, in __init__
    m_DirectoryInfo, blocksReader = self.read_fs(reader)
  File "C:\Development\Python\Python3.10.6\lib\site-packages\UnityPy\files\BundleFile.py", line 177, in read_fs
    b"".join(
  File "C:\Development\Python\Python3.10.6\lib\site-packages\UnityPy\files\BundleFile.py", line 178, in <genexpr>
    self.decompress_data(
  File "C:\Development\Python\Python3.10.6\lib\site-packages\UnityPy\files\BundleFile.py", line 517, in decompress_data
    return CompressionHelper.decompress_lz4(compressed_data, uncompressed_size)
  File "C:\Development\Python\Python3.10.6\lib\site-packages\UnityPy\helpers\CompressionHelper.py", line 91, in decompress_lz4
    return lz4.block.decompress(data, uncompressed_size)
_block.LZ4BlockError: Decompression failed: corrupt input or insufficient space in destination buffer. Error code: 5279
```
I COULD extract chart files, I couldn't extract the comics. I have not tried extracting anything else.

**Comment by YumYummity** [comment]
Trying out KR and seems one of the urls are wrong?

```python
  self.cache._update_abcache_index()
  File "C:\Development\Python\Python3.10.6\lib\site-packages\sssekai\abcache\__init__.py", line 515, in _update_abcache_index
    resp = self.request_packed("GET", self.SEKAI_AB_INFO_ENDPOINT)
  File "C:\Development\Python\Python3.10.6\lib\site-packages\sssekai\abcache\__init__.py", line 425, in request_packed
    resp.raise_for_status()
  File "C:\Development\Python\Python3.10.6\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://lf16-mkkr.bytedgame.com/obj/sf-game-alisg/gdl_app_292248/AssetBundle/3.4.1/Release/kr_online/android21/AssetBundleInfo.json
```

**Comment by mos9527** [comment]
Seems like I've missed a flag with the virtual file system. This is fixed now in https://github.com/mos9527/sssekai/commit/cfbb75cc5a5609e5474f8b0f5bd56b5d08854c30
<img width="1376" alt="image" src="https://github.com/user-attachments/assets/f96eb193-1878-48b1-a8f2-6322947823b8" />

> Is there any way to setup a guest account? (maybe with an email).
IIRC there was a lot of OAuth stuff involved. Honestly don't know if I can get this one working..I'll try though.

I'll take a look at the KR URL soon enough.

**Comment by mos9527** [comment]
https://github.com/mos9527/sssekai/commit/ba298e662026aba35d2f642d13a1066fc81e360e has implemented guest login for TW servers now. Though with the last stage of the login routine I kept getting 'Too many requests'...even from the game itself😵‍💫
Somehow proxies didn't fix that. I'll check again tomorrow.

**Comment by YumYummity** [comment]
Perhaps it might be easier to regenerate the access token? In the /login request a token is sent with it, I'm not sure what it is but perhaps it can be used to generate the user access token and go from there.

**Comment by YumYummity** [comment]
The KR version still does not work;
```python
    self.cache._update_abcache_index()
  File "C:\Development\Python\Python3.10.6\lib\site-packages\sssekai\abcache\__init__.py", line 524, in _update_abcache_index
    resp = self.request_packed("GET", self.SEKAI_AB_INFO_ENDPOINT)
  File "C:\Development\Python\Python3.10.6\lib\site-packages\sssekai\abcache\__init__.py", line 446, in request_packed
    resp.raise_for_status()
  File "C:\Development\Python\Python3.10.6\lib\site-packages\requests\models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://lf16-mkkr.bytedgame.com/obj/sf-game-alisg/gdl_app_292248/AssetBundle/3.4.1/Release/kr_online/android53/AssetBundleInfoNew.json
```

I checked the KR version and although it says "3.4.1" the correct fetch version is 3.4.0

**Comment by mos9527** [comment]
> I checked the KR version and although it says "3.4.1" the correct fetch version is 3.4.0

Unfortunately TW releases doesn't seem to have the game version aligned up with the Android package version...which is strange.
Maybe some other predictate for game version can be found in game assets (like Unity's Build config?) but meanwhile one may have to correct the version number themselves.

> Perhaps it might be easier to regenerate the access token? In the /login request a token is sent with it, I'm not sure what it is but perhaps it can be used to generate the user access token and go from there.

Actually this *is* the part where I got stuck on - there's another JWT token goes before it which isn't the one used in game.
Though trying to replay these requests resulted in `Too Many Requests`replies..I'll have another look.

**Comment by YumYummity** [comment]
> Actually this _is_ the part where I got stuck on - there's another JWT token goes before it which isn't the one used in game.
> Though trying to replay these requests resulted in `Too Many Requests`replies..I'll have another look.

Strange, I replayed the request once or twice and had no issues (only once or twice though.)

Also, for KR ABs, I'm still having issues extracting the content inside them. I can extract TW asset bundles with no issues now (thanks!) but for KR, there are no errors but there also isn't anything returned for when looking at this extractor (I'm using a slightly modified version).

https://github.com/pjsek-ai/pypjsekai/blob/master/src/pjsekai/asset_bundle.py

**Comment by mos9527** [comment]
Sorry for the late reply. But with some more trial and errors I've decided to **not implement ROW login routines in this repo.**
I'll post some of my findings here:

With some bisecting it's determined that `Too Many Requests` responses are a red herring of a failed signature check.
Requests sent from the game itself with either `X-Gorgon` or `X-Khronos` header missing would result in the said failure.
- `X-Khronos` is simply the request initation's UNIX timestamp in seconds.
- `X-Gorgon` seems to be a custom hash - which is (in)famously used in many of ByteDance's products such as TikTok and *all* ROW region releases of the game

The implementation of the latter seem to be updated all the time - for obvious reasons that would not be implemented directly in this repo. However, there _are_ white-room method that defeats this security measure without potential copyright issues:
- https://github.com/maiyao1988/ExAndroidNativeEmu/blob/master/example_douyin.py#L166

Historically there are completely reverse-engineered version of this algorithim too, but they don't work as of today:
- https://github.com/gaplan/TikTok-X-Gorgon/blob/main/xgorgon.py#L10

Lastly, here's some of the routines that was implemented besides the signature algorithm.
```python
def calc_x_gorgon(url, data, cookie=""):
    """Implementation goes here"""
    pass

from urllib.parse import urlencode
import json

AUTH_CONFIG_BYTEDANCE_TW = {
    "aid": 5245,
    "app_name": "pjsk_oversea",
    "app_package": "com.hermes.mk.asia",
    "sdk_app_id": 1782,
    "game_id": 5245,
}

def _generate_device_id():
    import uuid

    uid = uuid.uuid1().bytes[8:]
    uid = int.from_bytes(uid, "little")
    uid = str(uid).ljust(19, "0")
    return uid[:19]


__device_id = _generate_device_id()


def __gen_bytedance_headers(config: AbCacheConfig):
    auth_config = dict()
    match config.app_region:
        case "tw":
            auth_config = AUTH_CONFIG_BYTEDANCE_TW
        case _:
            raise NotImplementedError("Region not supported")
    return {
        "device_id": __device_id,
        "channel": "GooglePlay",
        "os": config.app_platform.lower(),
        **auth_config,
    }


def acc_logout_bytedance(config: AbCacheConfig, token: str):
    logger.info("Logging out from ByteDance servers")

    with AbCache(config) as session:
        params = __gen_bytedance_headers(config)
        params |= {
            "login_type": "home",
            "user_type": 1,
            "iid": __device_id,
        }
        resp = session.request(
            "POST",
            "https://gsdk-sg.bytegsdk.com/gsdk/account/logout",
            params=params,
            data={
                "device_id": __device_id,
                "token": token,
                "channel_id": "bsdkintl",
            },
            headers={
                "content-type": "application/x-www-form-urlencoded; charset=UTF-8"
            },
        )
        resp.raise_for_status()
        logger.info("Success. Token was=%s" % token)


def set_acc_bytedance(config: AbCacheConfig, user_id: str, token: str):
    logger.info("Logging into ByteDance servers")

    with AbCache(config) as session:
        params = __gen_bytedance_headers(config)
        params |= {
            "login_type": "home",
            "user_type": 1,
            "iid": __device_id,
        }
        data = {
            "device_id": __device_id,
            "data": json.dumps({"user_id": str(user_id), "token": token}),
            "channel_id": "bsdkintl",
        }
        params = urlencode(params)
        data = urlencode(data)
        url = f"https://gsdk-sg.bytegsdk.com/gsdk/account/login?{params}"
        gorgon = calc_x_gorgon(url, data)
        logger.debug("Gorgon=%s" % gorgon)
        resp = session.request(
            "POST",
            url,
            params=params,
            data=data,
            headers={
                "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
                "X-Gorgon": gorgon,
                "X-Khronos": str(int(time())),
            },
        )
        resp.raise_for_status()
        data = resp.json()
        if "data" in data:
            data = data["data"]
            logger.info("Success. AccessToken=%s" % data["access_token"])
            config.auth_userID = user_id
            config.auth_credential = data["access_token"]
            return config
        else:
            raise Exception("Failed to register user data: %s" % resp.text)


def set_anoymous_acc_bytedance(config: AbCacheConfig):
    logger.info("Registering user data")

    with AbCache(config) as session:
        params = __gen_bytedance_headers(config)
        params |= {
            "login_type": "home",
            "user_type": 1,
            "ui_flag": 1,
            "is_create": 0,
        }
        resp = session.request(
            "POST",
            "https://gsdk-sg.bytegsdk.com/sdk/account/visitor_login",
            params=params,
        )
        resp.raise_for_status()
        data = resp.json()
        if "data" in data:
            data = data["data"]
            logger.info(
                "Success. User =ID=%s, Token=%s" % (data["user_id"], data["token"])
            )
            acc_logout_bytedance(config, data["token"])
            return set_acc_bytedance(config, data["user_id"], data["token"])
        else:
            raise Exception("Failed to register user data: %s" % resp.text)
```

**Comment by mos9527** [comment]
> but for KR, there are no errors but there also isn't anything returned for when looking at this extractor (I'm using a slightly modified version).

This should be now fixed as of https://github.com/mos9527/sssekai/commit/04ad8a8857c764f211ca909bd6e0e216cb1236b5

**Comment by YumYummity** [comment]
Hi, thank you for the help!
